"""New Migration

Revision ID: 160d5cc3750e
Revises: 9cc6418239ce
Create Date: 2023-05-12 20:13:33.026255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '160d5cc3750e'
down_revision = '9cc6418239ce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
