"""New Migration

Revision ID: 5b2de35d92e7
Revises: 160d5cc3750e
Create Date: 2023-05-12 20:17:35.948932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b2de35d92e7'
down_revision = '160d5cc3750e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
