"""New Migration

Revision ID: 688ab50ba673
Revises: 868428d43bec
Create Date: 2023-05-12 18:12:18.277726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '688ab50ba673'
down_revision = '868428d43bec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Products', 'a')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Products', sa.Column('a', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
