"""New Migration

Revision ID: 868428d43bec
Revises: ae16b4c147a1
Create Date: 2023-05-12 18:11:51.160693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '868428d43bec'
down_revision = 'ae16b4c147a1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Products', sa.Column('a', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Products', 'a')
    # ### end Alembic commands ###
