"""New Migration

Revision ID: 9cc6418239ce
Revises: 688ab50ba673
Create Date: 2023-05-12 20:02:52.791979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cc6418239ce'
down_revision = '688ab50ba673'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('username', sa.String(length=8), nullable=True))
    op.add_column('Users', sa.Column('hashed_password', sa.Integer(), nullable=True))
    op.add_column('Users', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'email')
    op.drop_column('Users', 'hashed_password')
    op.drop_column('Users', 'username')
    # ### end Alembic commands ###
