"""New Migration

Revision ID: c323cccb0564
Revises: 5b2de35d92e7
Create Date: 2023-05-12 20:17:55.279488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c323cccb0564'
down_revision = '5b2de35d92e7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('hashed_password', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
